apiVersion: v1
kind: Service
metadata:
    name: "afxoakscluster-1f0f"
    labels:
        app: "afxoakscluster-1f0f"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "afxoakscluster-1f0f"