apiVersion: v1
kind: Service
metadata:
  name: afxo-service
  namespace: afxo-namespace
  labels:
    app: afxo-app
spec:
  selector:
    app: afxo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: afxo-deployment
  namespace: afxo-namespace
  labels:
    app: afxo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: afxo-app
  template:
    metadata:
      labels:
        app: afxo-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: nginx:1.19.2
        ports:
        - containerPort: 80