on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: afxoazurecontainerregistry.azurecr.io
        username: ${{ secrets.acr_afxoazurecontainerregistry_username }}
        password: ${{ secrets.acr_afxoazurecontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "https://github.com/jboukos/afxotec" -t afxoazurecontainerregistry.azurecr.io/afxoakscluster:${{ github.sha }}
        docker push afxoazurecontainerregistry.azurecr.io/afxoakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_afxoakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep afxoaksclusterbd98 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace afxoaksclusterbd98`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: afxoaksclusterbd98
        container-registry-url: afxoazurecontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_afxoazurecontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_afxoazurecontainerregistry_password }}
        secret-name: afxoaksclustdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: afxoaksclusterbd98
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          afxoazurecontainerregistry.azurecr.io/afxoakscluster:${{ github.sha }}
        imagepullsecrets: |
          afxoaksclustdockerauth
